### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by arm-on** [hsouri/Sleeper-Agent#7]
Dear Hossein,
I was trying to reproduce the results of the paper. I ran the code on Kaggle:
https://www.kaggle.com/code/malekzadeharman/sleeper-agent-original-code/notebook
As you can see from the link above, I get the following error:
`Traceback (most recent call last):
  File "/kaggle/working/Sleeper-Agent/sleeper_agent.py", line 47, in <module>
    poison_delta = witch.brew(model, data)
  File "/kaggle/working/Sleeper-Agent/forest/witchcoven/witch_base.py", line 49, in brew
    poison_delta = self._brew(victim, kettle)
  File "/kaggle/working/Sleeper-Agent/forest/witchcoven/witch_base.py", line 73, in _brew
    poison_delta, source_losses = self._run_trial(victim, kettle)
  File "/kaggle/working/Sleeper-Agent/forest/witchcoven/witch_base.py", line 187, in _run_trial
    loss, prediction = self._batched_step(poison_delta, poison_bounds, example, victim, kettle)
  File "/kaggle/working/Sleeper-Agent/forest/witchcoven/witch_base.py", line 338, in _batched_step
    poison_delta.grad[poison_slices] = delta_slice.grad.detach().to(device=torch.device('cpu'))
TypeError: 'NoneType' object does not support item assignment`

Could you please elaborate on this? What is the problem?

**Comment by Chen-Zhiwei** [comment]
I meet the same problem. I change the optimizer but it is not work for successful attack.
